- hosts: '{{ target }}'
  tasks:
    - name: Rescanning nextcloud filesystem
      shell:
        cmd: 'docker exec --user www-data {{ nextcloud_conainer_name }} php occ files:scan --all'
      register: cmd_output

    - debug:
        msg: '{{ cmd_output }}'